[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]
aptPkgs = ["git", "python3", "python3-pip", "build-essential", "python-is-python3"]

[phases.install]
cmds = ["npm ci --omit=dev --no-optional --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]
dependsOn = ["install"]

[start]
cmd = "npm run start"
dependsOn = ["build"]

[variables]
NODE_ENV = "production"
PORT = "3000"
NPM_CONFIG_ENGINE_STRICT = "false"
NODE_OPTIONS = "--max_old_space_size=4096"
PYTHON = "python3"
NPM_CONFIG_OPTIONAL = "false"