[build]
builder = "nixpacks"
installCommand = "npm ci --omit=dev"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"
PORT = "3000"
NPM_CONFIG_ENGINE_STRICT = "false"